x-base-image:   &base-image   gitlab.ika.rwth-aachen.de:5050/automated-driving/docker/ros1:latest
x-devel-image:  &devel-image  gitlab.ika.rwth-aachen.de:5050/github/mqtt_client:latest-dev
x-run-image:    &run-image    gitlab.ika.rwth-aachen.de:5050/github/mqtt_client:latest
x-command:      &command      roslaunch mqtt_client standalone.launch

# ==============================================================================

x-build: &build
  dockerfile: ./docker/docker-ros/Dockerfile
  context: ../
  args:
    BASE_IMAGE: *base-image
    COMMAND: *command

services:
  devel:
    image: *devel-image
    build:
      target: development
      <<: *build
  run:
    image: *run-image
    build:
      target: run
      <<: *build