x-base-image: &base-image gitlab.ika.rwth-aachen.de:5050/automated-driving/docker/ros1:latest  # e.g. gitlab.ika.rwth-aachen.de:5050/automated-driving/docker/ros2:latest
x-dev-image:  &dev-image  gitlab.ika.rwth-aachen.de:5050/github/mqtt_client:latest-dev   # e.g. gitlab.ika.rwth-aachen.de:5050/ops/hello_world:latest-dev
x-run-image:  &run-image  gitlab.ika.rwth-aachen.de:5050/github/mqtt_client:latest   # e.g. gitlab.ika.rwth-aachen.de:5050/ops/hello_world:latest
x-command:    &command    roslaunch mqtt_client standalone.launch     # e.g. ros2 topic pub "/ping" "std_msgs/msg/String" "{data: Hello World}"

# ==============================================================================

x-build: &build
  dockerfile: ./docker/docker-ros/Dockerfile
  context: ../
  args:
    BASE_IMAGE: *base-image
    COMMAND: *command
    GIT_HTTPS_USER: $GIT_HTTPS_USER
    GIT_HTTPS_PASSWORD: $GIT_HTTPS_PASSWORD

services:
  dev:
    image: *dev-image
    build:
      target: dev
      <<: *build
  run:
    image: *run-image
    build:
      target: run
      <<: *build
