name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup catkin
        uses: betwo/github-setup-catkin@master
        with:
          ros-version: noetic
          build-tool: catkin_tools
          workspace: $GITHUB_WORKSPACE
      - name: Build ROS workspace
        run: catkin build
